export { buildOpenApiDocument, type OpenApiOptions } from './openapi.js';
export { ACTION_BY_ID, type ActionID, ALL_ACTIONS } from './registry.js';
export { isScope, SCOPES, type Scope, scopeImplies } from './scopes.js';
export {
  assignTicketInputSchema,
  attachmentInputSchema,
  attachmentSchema,
  createTicketInputSchema,
  messageCreateInputSchema,
  messageIdInputSchema,
  messageOutputSchema,
  messageUpdateInputSchema,
  snoozeTicketInputSchema,
  TICKET_ACTIONS,
  type TicketAction,
  type TicketActionID,
  ticketActions,
  ticketBaseSchema,
  ticketCustomerSchema,
  ticketCustomFieldSetInputSchema,
  ticketCustomFieldSetOutputSchema,
  ticketCustomFieldValueSchema,
  ticketDetailSchema,
  ticketIdInputSchema,
  ticketMessageSchema,
  ticketOutputSchema,
  ticketPrioritySchema,
  ticketSchema,
  ticketStatusSchema,
  ticketSummarySchema,
  ticketsListInputSchema,
  ticketsListOutputSchema,
  ticketTagRemoveInputSchema,
  ticketTagsInputSchema,
  ticketTagsOutputSchema,
  updateTicketInputSchema,
} from './tickets.js';
export {
  type ActionContract,
  type ActionInput,
  type ActionOutput,
  type AnyActionContract,
  defineAction,
  type HttpMethod,
  type IdempotencyPolicy,
} from './types.js';
